[package]
name = "zvs"
version = "0.1.0"
edition = "2021"
description = "Stateless Zcash Verification Service"
license = "MIT"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tonic = "0.11"
prost = "0.12"
zcash_primitives = "0.13"
bech32 = "0.9"
hex = "0.4"
anyhow = "1"

[build-dependencies]
tonic-build = "0.11"
